# Travis CI config

# Note: When updating, please also update .gitlab-ci.yml
language: python
dist: xenial  # required for Python >= 3.7
env:
  TOOLCHAIN_DIR="${HOME}/toolchain"

  ESP8266_BINDIR="${TOOLCHAIN_DIR}/xtensa-lx106-elf/bin"
  ESP32_BINDIR="${TOOLCHAIN_DIR}/xtensa-esp32-elf/bin"
  ESP32S2_BINDIR="${TOOLCHAIN_DIR}/xtensa-esp32s2-elf/bin"

  PATH="${PATH}:${ESP8266_BINDIR}:${ESP32_BINDIR}:${ESP32S2_BINDIR}"

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  # no requirements.txt in esptool, and so remove the default install step from all jobs

stages:
  - name: test

jobs:
  include:
    stage: test
    install:
    script:
      # test python components (fast)
      - python setup.py build
